# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/kida925e/Final_submission/Conv_opt_vivado/Conv_opt_vivado.srcs/sources_1/bd/design_1/ip/design_1_Conv_1_0/design_1_Conv_1_0.xci
# IP: The module: 'design_1_Conv_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kida925e/Final_submission/Conv_opt_vivado/Conv_opt_vivado.srcs/sources_1/bd/design_1/ip/design_1_Conv_1_0/constraints/Conv_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_Conv_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/kida925e/Final_submission/Conv_opt_vivado/Conv_opt_vivado.srcs/sources_1/bd/design_1/ip/design_1_Conv_1_0/design_1_Conv_1_0.xci
# IP: The module: 'design_1_Conv_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/kida925e/Final_submission/Conv_opt_vivado/Conv_opt_vivado.srcs/sources_1/bd/design_1/ip/design_1_Conv_1_0/constraints/Conv_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_Conv_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
